### ISSUE TITLE
Running with pm2

### ISSUE THREAD

**Issue by DarknesS755** [HerrEurobeat/steam-idler#10]
Is it possible to start the program using pm2 so that the boost process does not stop when the terminal window is closed. 
In my case, there is an error :
```
6|idler  | TypeError: process.stdout.moveCursor is not a function
6|idler  |     at module.exports.log (/root/steam-idler-main/node_modules/output-logger/lib/helpers/printManager.js:80:24)
6|idler  |     at module.exports.handleExit (/root/steam-idler-main/node_modules/output-logger/lib/events.js:33:27)
6|idler  |     at process.on.events.<computed> (/root/steam-idler-main/node_modules/output-logger/index.js:125:68)
6|idler  |     at process.emit (node:events:511:28)

6|idler  | TypeError: process.stdout.moveCursor is not a function
6|idler  |     at module.exports.log (/root/steam-idler-main/node_modules/output-logger/lib/helpers/printManager.js:80:24)
6|idler  |     at module.exports.logger (/root/steam-idler-main/node_modules/output-logger/lib/logger.js:101:27)
6|idler  |     at module.exports (/root/steam-idler-main/node_modules/output-logger/index.js:35:39)
6|idler  |     at module.exports.start (/root/steam-idler-main/src/controller.js:79:5)
6|idler  |     at Object.<anonymous> (/root/steam-idler-main/idler.js:19:32)
6|idler  |     at Module._compile (node:internal/modules/cjs/loader:1255:14)
6|idler  |     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
6|idler  |     at Module.load (node:internal/modules/cjs/loader:1113:32)
6|idler  |     at Module._load (node:internal/modules/cjs/loader:960:12)
6|idler  |     at Object.<anonymous> (/root/.n/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
```

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue! This is a known issue with pm2 not supporting certain stdout functions:  
https://github.com/HerrEurobeat/steam-comment-service-bot/issues/48  

I still need to find a workaround in my logging library, I'll keep you updated.

**Comment by HerrEurobeat** [comment]
Version 1.6 is out which fixes this issue. Please let me know if I missed something!
